# Generated by Django 5.2.7 on 2025-11-14 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_management_module', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='achievement_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='recommendation_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_budget',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('General', 'General'), ('Achievement', 'Achievement'), ('Recommendation', 'Recommendation')], default='General', max_length=50),
        ),
    ]
