# Generated by Django 5.2.7 on 2025-11-14 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_management_module', '0003_budget_status'),
        ('notification_management_module', '0004_notification_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='related_budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget_management_module.budget'),
        ),
    ]
