# Generated by Django 5.2.7 on 2025-10-25 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_management_module', '0003_budget_status'),
        ('expense_management_module', '0003_expense_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='budget_management_module.budget'),
        ),
    ]
