# Generated by Django 5.2.7 on 2025-11-14 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_management_module', '0003_budget_status'),
        ('expense_management_module', '0004_alter_expense_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='budget_management_module.budget'),
        ),
    ]
