# Generated by Django 5.2.5 on 2025-11-17 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_management_module', '0005_remove_budget_notification_sent'),
        ('expense_management_module', '0005_alter_expense_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='budget_management_module.budget'),
        ),
    ]
