# Generated by Django 5.2.7 on 2025-10-11 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_module', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
