# Generated by Django 5.2.7 on 2025-10-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_module', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
