# Generated by Django 5.2.7 on 2025-10-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_management_module', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('full', 'Full')], default='active', max_length=15),
        ),
    ]
