# Generated by Django 5.2.7 on 2025-11-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_management_module', '0003_budget_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
