# Generated by Django 5.2.7 on 2025-11-16 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_management_module', '0004_budget_notification_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='notification_sent',
        ),
    ]
