# Generated by Django 5.2.5 on 2025-11-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_management_module', '0005_remove_budget_notification_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='limit_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
